name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: cd docs && npm ci

      # ▼▼▼▼▼【修正】ここからデバッグと置換処理▼▼▼▼▼
      - name: 1. Check current directory and file existence
        run: |
          pwd
          ls -R ./docs

      - name: 2. Show <br> tags BEFORE replacement
        # grep will exit with 1 if no lines are found, so we add `|| true` to prevent the job from failing here.
        run: |
          echo "--- Searching for <br> in all .md files before replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: 3. Replace <br> with <br />
        # Use a simpler, more compatible sed command. Using # as a delimiter avoids issues with /.
        run: |
          find ./docs -type f -name "*.md" -exec sed -i 's#<br>#<br />#g' {} +
          echo "Replacement command executed."

      - name: 4. Show <br> tags AFTER replacement
        run: |
          echo "--- Searching for <br> in all .md files after replacement ---"
          grep -r --color=auto "<br>" ./docs || true
      # ▲▲▲▲▲【修正】ここまでデバッグと置換処理▲▲▲▲▲

      - name: Test build website
        run: cd docs && npm run build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json
          
      - name: Install dependencies
        run: cd docs && npm ci

      # ▼▼▼▼▼【修正】ここからデバッグと置換処理▼▼▼▼▼
      - name: 1. Check current directory and file existence
        run: |
          pwd
          ls -R ./docs
          
      - name: 2. Show <br> tags BEFORE replacement
        run: |
          echo "--- Searching for <br> in all .md files before replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: 3. Replace <br> with <br />
        run: |
          find ./docs -type f -name "*.md" -exec sed -i 's#<br>#<br />#g' {} +
          echo "Replacement command executed."

      - name: 4. Show <br> tags AFTER replacement
        run: |
          echo "--- Searching for <br> in all .md files after replacement ---"
          grep -r --color=auto "<br>" ./docs || true
      # ▲▲▲▲▲【修正】ここまでデバッグと置換処理▲▲▲▲▲

      - name: Build website
        run: cd docs && npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
